const AUTH_SET_IS_LOGIN = 'AUTH SET_IS_LOGIN';
const AUTH_SET_TOKEN = 'AUTH SET_TOKEN';
const AUTH_LOGOUT = 'AUTH LOGOUT';
const AUTH_SET_USER = 'AUTH SET_USER';

export {
  AUTH_SET_IS_LOGIN,
  AUTH_SET_TOKEN,
  AUTH_LOGOUT,
  AUTH_SET_USER
}